// GOLDEN PARITY TEST. Asserts the TypeScript analysis port reproduces the live
// Python analysis (src/analysis/stage.py, screener.py) bar-for-bar on an
// identical multi-stage series. Fixture is generated by
// `python scripts/gen_chart_parity_fixture.py` (re-run if the Python changes).
//
// Tolerances absorb Python's banker's-rounding vs JS half-up on the already-
// rounded scalars Python exposes (ma150 2dp, slope 2dp, range/rsi 1dp, rs 4dp);
// integers/booleans are compared exactly.
import { describe, expect, it } from "vitest";
import fixture from "./__fixtures__/parity.json";
import {
  computeStageBars,
  rsSeries,
  rsi14Cutler,
  round,
} from "./analysis";

const { closes, bench, dates, expected } = fixture as {
  closes: number[];
  bench: number[];
  dates: string[];
  expected: {
    per_bar_stage: (number | null)[];
    latest: {
      stage: number | null;
      ma150: number | null;
      above_ma: boolean;
      ma_slope_pct: number | null;
      range_pos: number | null;
      rsi14: number | null;
      days: number;
    };
    rs_latest: { rs: number | null; new_high: boolean };
    rsi_latest: number | null;
    rs_probe: Record<string, { rs: number | null; new_high: boolean }>;
  };
};

describe("analysis.ts parity with Python", () => {
  const stageBars = computeStageBars(closes, dates);
  const rs = rsSeries(closes, bench, dates);
  const last = stageBars[stageBars.length - 1];

  it("classifies every bar's Weinstein stage identically", () => {
    expect(stageBars.length).toBe(expected.per_bar_stage.length);
    const mismatches: string[] = [];
    for (let i = 0; i < stageBars.length; i++) {
      if ((stageBars[i].stage ?? null) !== (expected.per_bar_stage[i] ?? null)) {
        mismatches.push(`bar ${i}: ts=${stageBars[i].stage} py=${expected.per_bar_stage[i]}`);
      }
    }
    expect(mismatches.slice(0, 10)).toEqual([]);
  });

  it("matches the latest-bar scalars", () => {
    expect(last.stage).toBe(expected.latest.stage);
    expect(last.aboveMa).toBe(expected.latest.above_ma);
    // ma150 (2dp) — recompute the rounded latest MA from the point series.
    expect(round(last.maSlopePct as number, 2)).toBeCloseTo(expected.latest.ma_slope_pct as number, 1);
    expect(round(last.rangePos as number, 1)).toBeCloseTo(expected.latest.range_pos as number, 0);
  });

  it("matches Cutler RSI(14) at the latest bar", () => {
    const rsi = rsi14Cutler(closes);
    expect(rsi).not.toBeNull();
    expect(rsi as number).toBeCloseTo(expected.rsi_latest as number, 1);
  });

  it("matches the RS line + new-high flag at the latest bar", () => {
    const rsLast = rs[rs.length - 1];
    expect(rsLast.rs).toBeCloseTo(expected.rs_latest.rs as number, 4);
    expect(rsLast.newHigh).toBe(expected.rs_latest.new_high);
  });

  it("matches RS new-high flag at probe indices", () => {
    for (const [idxStr, exp] of Object.entries(expected.rs_probe)) {
      const i = Number(idxStr);
      expect(rs[i].rs).toBeCloseTo(exp.rs as number, 4);
      expect(rs[i].newHigh).toBe(exp.new_high);
    }
  });
});
